# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3bfe7d1a420b60c9eb07c413237fa0ea84baff88e690bb536b6c43900584971ab60e6d00a18ccea8b27a3829e2977b6342dd5dfa2e497fd532a72a952d1266f

test:
  secret_key_base: efb4f9a6335e078cffe73a2eb35d111266c9b6424a71bea0d16b1f777d1e46e0880be64a3a57b506a4b7c65cd6ab7c48958bcd2e470d70e4d53757cc261d1bd6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
